# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4116a78d39ed44acff8deb73a599441b22ce00462742b0a5d36bd7a1f8fe13f4463388cf71d0ab10810c577789b6588cd086f880bcda0db94d25dbf188fc896b

test:
  secret_key_base: 4269bc313b72271d53a7d6014dba4335552ee5f19f031904e275f9db41ab5140b4823ab2b789526d2a7bb9823bb614f6e63856b34f88704b1b01e8ad30ad578b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
